---
- hosts: kgs
  become: yes
  gather_facts: False

  vars:
    SUNET:
      - ktully
      - dvelasqu
      - jeff888
      - kalanit
      - dfinzi
      - mgrotheer
      - eshedm
      - rosenke
      - arezai98
      - sonia09
      - mnordt
      - frq
      - ekubota
      - insubkim
      - hkular
      - vnatu
      - haji
      - ekupers

  tasks:
    
    - name: Validate canonical permissions of krb5.conf
      file:
        path: /etc/krb5.conf
        owner: root
        group: root
        mode: '0644'

    - name: Validate canonical permissions of krb5.keytab
      file:
        path: /etc/krb5.keytab
        owner: root
        group: root
        mode: '0600'

    - name: Validate canonical permissions of oak native mount point
      file:
        path: /oak/stanford/groups/
        state: directory
        owner: root
        group: oak_kalanit
        mode: '755'

    - name: Add oak_kalanit group
      group:
        name: "oak_kalanit"
        state: present 

    - name: Ensure all lab members are a member of oak_kalanit
      user:
        name: "{{item}}"
        groups: oak_kalanit
        append: yes
      with_items: "{{SUNET}}"